language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules
    - test/smoke/template/node_modules

node_js: stable

install:
  - yarn
  - cd ./test/smoke/template
  - yarn 
  - cd ../../..

scripts:
  - npm test